import torch
from torch.nn.parameter import Parameter

def split_conv_128(conv_tensor):
    x1 = conv_tensor.narrow(2, 0, 1).narrow(3, 0, 1)
    x2 = conv_tensor.narrow(2, 1, 1).narrow(3, 0, 1)
    x3 = conv_tensor.narrow(2, 2, 1).narrow(3, 0, 1)
    x4 = conv_tensor.narrow(2, 0, 1).narrow(3, 1, 1)
    x5 = conv_tensor.narrow(2, 1, 1).narrow(3, 1, 1)
    x6 = conv_tensor.narrow(2, 2, 1).narrow(3, 1, 1)
    x7 = conv_tensor.narrow(2, 0, 1).narrow(3, 2, 1)
    x8 = conv_tensor.narrow(2, 1, 1).narrow(3, 2, 1)
    x9 = conv_tensor.narrow(2, 2, 1).narrow(3, 2, 1)

    return x1,x2,x3,x4,x5,x6,x7,x8,x9

def split_conv_256(conv_tensor):
    x1 = conv_tensor.narrow(2, 0, 1).narrow(3, 0, 1).narrow(1, 0, 128)
    x2 = conv_tensor.narrow(2, 1, 1).narrow(3, 0, 1).narrow(1, 0, 128)
    x3 = conv_tensor.narrow(2, 2, 1).narrow(3, 0, 1).narrow(1, 0, 128)
    x4 = conv_tensor.narrow(2, 0, 1).narrow(3, 1, 1).narrow(1, 0, 128)
    x5 = conv_tensor.narrow(2, 1, 1).narrow(3, 1, 1).narrow(1, 0, 128)
    x6 = conv_tensor.narrow(2, 2, 1).narrow(3, 1, 1).narrow(1, 0, 128)
    x7 = conv_tensor.narrow(2, 0, 1).narrow(3, 2, 1).narrow(1, 0, 128)
    x8 = conv_tensor.narrow(2, 1, 1).narrow(3, 2, 1).narrow(1, 0, 128)
    x9 = conv_tensor.narrow(2, 2, 1).narrow(3, 2, 1).narrow(1, 0, 128)
    x12 = conv_tensor.narrow(2, 0, 1).narrow(3, 0, 1).narrow(1, 128, 128)
    x22 = conv_tensor.narrow(2, 1, 1).narrow(3, 0, 1).narrow(1, 128, 128)
    x32 = conv_tensor.narrow(2, 2, 1).narrow(3, 0, 1).narrow(1, 128, 128)
    x42 = conv_tensor.narrow(2, 0, 1).narrow(3, 1, 1).narrow(1, 128, 128)
    x52 = conv_tensor.narrow(2, 1, 1).narrow(3, 1, 1).narrow(1, 128, 128)
    x62 = conv_tensor.narrow(2, 2, 1).narrow(3, 1, 1).narrow(1, 128, 128)
    x72 = conv_tensor.narrow(2, 0, 1).narrow(3, 2, 1).narrow(1, 128, 128)
    x82 = conv_tensor.narrow(2, 1, 1).narrow(3, 2, 1).narrow(1, 128, 128)
    x92 = conv_tensor.narrow(2, 2, 1).narrow(3, 2, 1).narrow(1, 128, 128)

    return x1,x2,x3,x4,x5,x6,x7,x8,x9,x12,x22,x32,x42,x52,x62,x72,x82,x92

def split_conv_512(conv_tensor):
    x1 = conv_tensor.narrow(2, 0, 1).narrow(3, 0, 1).narrow(1, 0, 128)
    x2 = conv_tensor.narrow(2, 1, 1).narrow(3, 0, 1).narrow(1, 0, 128)
    x3 = conv_tensor.narrow(2, 2, 1).narrow(3, 0, 1).narrow(1, 0, 128)
    x4 = conv_tensor.narrow(2, 0, 1).narrow(3, 1, 1).narrow(1, 0, 128)
    x5 = conv_tensor.narrow(2, 1, 1).narrow(3, 1, 1).narrow(1, 0, 128)
    x6 = conv_tensor.narrow(2, 2, 1).narrow(3, 1, 1).narrow(1, 0, 128)
    x7 = conv_tensor.narrow(2, 0, 1).narrow(3, 2, 1).narrow(1, 0, 128)
    x8 = conv_tensor.narrow(2, 1, 1).narrow(3, 2, 1).narrow(1, 0, 128)
    x9 = conv_tensor.narrow(2, 2, 1).narrow(3, 2, 1).narrow(1, 0, 128)
    x12 = conv_tensor.narrow(2, 0, 1).narrow(3, 0, 1).narrow(1, 128, 128)
    x22 = conv_tensor.narrow(2, 1, 1).narrow(3, 0, 1).narrow(1, 128, 128)
    x32 = conv_tensor.narrow(2, 2, 1).narrow(3, 0, 1).narrow(1, 128, 128)
    x42 = conv_tensor.narrow(2, 0, 1).narrow(3, 1, 1).narrow(1, 128, 128)
    x52 = conv_tensor.narrow(2, 1, 1).narrow(3, 1, 1).narrow(1, 128, 128)
    x62 = conv_tensor.narrow(2, 2, 1).narrow(3, 1, 1).narrow(1, 128, 128)
    x72 = conv_tensor.narrow(2, 0, 1).narrow(3, 2, 1).narrow(1, 128, 128)
    x82 = conv_tensor.narrow(2, 1, 1).narrow(3, 2, 1).narrow(1, 128, 128)
    x92 = conv_tensor.narrow(2, 2, 1).narrow(3, 2, 1).narrow(1, 128, 128)
    x13 = conv_tensor.narrow(2, 0, 1).narrow(3, 0, 1).narrow(1, 256, 128)
    x23 = conv_tensor.narrow(2, 1, 1).narrow(3, 0, 1).narrow(1, 256, 128)
    x33 = conv_tensor.narrow(2, 2, 1).narrow(3, 0, 1).narrow(1, 256, 128)
    x43 = conv_tensor.narrow(2, 0, 1).narrow(3, 1, 1).narrow(1, 256, 128)
    x53 = conv_tensor.narrow(2, 1, 1).narrow(3, 1, 1).narrow(1, 256, 128)
    x63 = conv_tensor.narrow(2, 2, 1).narrow(3, 1, 1).narrow(1, 256, 128)
    x73 = conv_tensor.narrow(2, 0, 1).narrow(3, 2, 1).narrow(1, 256, 128)
    x83 = conv_tensor.narrow(2, 1, 1).narrow(3, 2, 1).narrow(1, 256, 128)
    x93 = conv_tensor.narrow(2, 2, 1).narrow(3, 2, 1).narrow(1, 256, 128)
    x14 = conv_tensor.narrow(2, 0, 1).narrow(3, 0, 1).narrow(1, 384, 128)
    x24 = conv_tensor.narrow(2, 1, 1).narrow(3, 0, 1).narrow(1, 384, 128)
    x34 = conv_tensor.narrow(2, 2, 1).narrow(3, 0, 1).narrow(1, 384, 128)
    x44 = conv_tensor.narrow(2, 0, 1).narrow(3, 1, 1).narrow(1, 384, 128)
    x54 = conv_tensor.narrow(2, 1, 1).narrow(3, 1, 1).narrow(1, 384, 128)
    x64 = conv_tensor.narrow(2, 2, 1).narrow(3, 1, 1).narrow(1, 384, 128)
    x74 = conv_tensor.narrow(2, 0, 1).narrow(3, 2, 1).narrow(1, 384, 128)
    x84 = conv_tensor.narrow(2, 1, 1).narrow(3, 2, 1).narrow(1, 384, 128)
    x94 = conv_tensor.narrow(2, 2, 1).narrow(3, 2, 1).narrow(1, 384, 128)

    return x1,x2,x3,x4,x5,x6,x7,x8,x9,x12,x22,x32,x42,x52,x62,x72,x82,x92,x13,x23,x33,x43,x53,x63,x73,x83,x93,x14,x24,x34,x44,x54,x64,x74,x84,x94

def split_model_conv(model, model_baseline):

    for name, param in model_baseline['state_dict'].items():
        own_state = model.state_dict()

        if name == 'conv1.weight': #skip the first layer
            own_state[name].copy_(param)
            continue

        if name == 'layer1.0.conv1.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9 = split_conv_128(param)
            own_state['layer1.0.conv1.weight'].copy_(x1)
            own_state['layer1.0.conv2.weight'].copy_(x2)
            own_state['layer1.0.conv3.weight'].copy_(x3)
            own_state['layer1.0.conv4.weight'].copy_(x4)
            own_state['layer1.0.conv5.weight'].copy_(x5)
            own_state['layer1.0.conv6.weight'].copy_(x6)
            own_state['layer1.0.conv7.weight'].copy_(x7)
            own_state['layer1.0.conv8.weight'].copy_(x8)
            own_state['layer1.0.conv9.weight'].copy_(x9)
            continue

        if name == 'layer1.0.conv2.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9 = split_conv_128(param)
            own_state['layer1.0.conv1_2.weight'].copy_(x1)
            own_state['layer1.0.conv2_2.weight'].copy_(x2)
            own_state['layer1.0.conv3_2.weight'].copy_(x3)
            own_state['layer1.0.conv4_2.weight'].copy_(x4)
            own_state['layer1.0.conv5_2.weight'].copy_(x5)
            own_state['layer1.0.conv6_2.weight'].copy_(x6)
            own_state['layer1.0.conv7_2.weight'].copy_(x7)
            own_state['layer1.0.conv8_2.weight'].copy_(x8)
            own_state['layer1.0.conv9_2.weight'].copy_(x9)
            continue

        if name == 'layer1.1.conv1.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9 = split_conv_128(param)
            own_state['layer1.1.conv1.weight'].copy_(x1)
            own_state['layer1.1.conv2.weight'].copy_(x2)
            own_state['layer1.1.conv3.weight'].copy_(x3)
            own_state['layer1.1.conv4.weight'].copy_(x4)
            own_state['layer1.1.conv5.weight'].copy_(x5)
            own_state['layer1.1.conv6.weight'].copy_(x6)
            own_state['layer1.1.conv7.weight'].copy_(x7)
            own_state['layer1.1.conv8.weight'].copy_(x8)
            own_state['layer1.1.conv9.weight'].copy_(x9)
            continue

        if name == 'layer1.1.conv2.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9 = split_conv_128(param)
            own_state['layer1.1.conv1_2.weight'].copy_(x1)
            own_state['layer1.1.conv2_2.weight'].copy_(x2)
            own_state['layer1.1.conv3_2.weight'].copy_(x3)
            own_state['layer1.1.conv4_2.weight'].copy_(x4)
            own_state['layer1.1.conv5_2.weight'].copy_(x5)
            own_state['layer1.1.conv6_2.weight'].copy_(x6)
            own_state['layer1.1.conv7_2.weight'].copy_(x7)
            own_state['layer1.1.conv8_2.weight'].copy_(x8)
            own_state['layer1.1.conv9_2.weight'].copy_(x9)
            continue

        if name == 'layer2.0.conv1.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9 = split_conv_128(param)
            own_state['layer2.0.conv1.weight'].copy_(x1)
            own_state['layer2.0.conv2.weight'].copy_(x2)
            own_state['layer2.0.conv3.weight'].copy_(x3)
            own_state['layer2.0.conv4.weight'].copy_(x4)
            own_state['layer2.0.conv5.weight'].copy_(x5)
            own_state['layer2.0.conv6.weight'].copy_(x6)
            own_state['layer2.0.conv7.weight'].copy_(x7)
            own_state['layer2.0.conv8.weight'].copy_(x8)
            own_state['layer2.0.conv9.weight'].copy_(x9)
            continue

        if name == 'layer2.0.conv2.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9 = split_conv_128(param)
            own_state['layer2.0.conv1_2.weight'].copy_(x1)
            own_state['layer2.0.conv2_2.weight'].copy_(x2)
            own_state['layer2.0.conv3_2.weight'].copy_(x3)
            own_state['layer2.0.conv4_2.weight'].copy_(x4)
            own_state['layer2.0.conv5_2.weight'].copy_(x5)
            own_state['layer2.0.conv6_2.weight'].copy_(x6)
            own_state['layer2.0.conv7_2.weight'].copy_(x7)
            own_state['layer2.0.conv8_2.weight'].copy_(x8)
            own_state['layer2.0.conv9_2.weight'].copy_(x9)
            continue

        if name == 'layer2.1.conv1.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9 = split_conv_128(param)
            own_state['layer2.1.conv1.weight'].copy_(x1)
            own_state['layer2.1.conv2.weight'].copy_(x2)
            own_state['layer2.1.conv3.weight'].copy_(x3)
            own_state['layer2.1.conv4.weight'].copy_(x4)
            own_state['layer2.1.conv5.weight'].copy_(x5)
            own_state['layer2.1.conv6.weight'].copy_(x6)
            own_state['layer2.1.conv7.weight'].copy_(x7)
            own_state['layer2.1.conv8.weight'].copy_(x8)
            own_state['layer2.1.conv9.weight'].copy_(x9)
            continue

        if name == 'layer2.1.conv2.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9 = split_conv_128(param)
            own_state['layer2.1.conv1_2.weight'].copy_(x1)
            own_state['layer2.1.conv2_2.weight'].copy_(x2)
            own_state['layer2.1.conv3_2.weight'].copy_(x3)
            own_state['layer2.1.conv4_2.weight'].copy_(x4)
            own_state['layer2.1.conv5_2.weight'].copy_(x5)
            own_state['layer2.1.conv6_2.weight'].copy_(x6)
            own_state['layer2.1.conv7_2.weight'].copy_(x7)
            own_state['layer2.1.conv8_2.weight'].copy_(x8)
            own_state['layer2.1.conv9_2.weight'].copy_(x9)
            continue

        if name == 'layer3.0.conv1.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9 = split_conv_128(param)
            own_state['layer3.0.conv1.weight'].copy_(x1)
            own_state['layer3.0.conv2.weight'].copy_(x2)
            own_state['layer3.0.conv3.weight'].copy_(x3)
            own_state['layer3.0.conv4.weight'].copy_(x4)
            own_state['layer3.0.conv5.weight'].copy_(x5)
            own_state['layer3.0.conv6.weight'].copy_(x6)
            own_state['layer3.0.conv7.weight'].copy_(x7)
            own_state['layer3.0.conv8.weight'].copy_(x8)
            own_state['layer3.0.conv9.weight'].copy_(x9)
            continue

        if name == 'layer3.0.conv2.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9,x12,x22,x32,x42,x52,x62,x72,x82,x92 = split_conv_256(param)
            own_state['layer3.0.conv1_2.weight'].copy_(x1)
            own_state['layer3.0.conv2_2.weight'].copy_(x2)
            own_state['layer3.0.conv3_2.weight'].copy_(x3)
            own_state['layer3.0.conv4_2.weight'].copy_(x4)
            own_state['layer3.0.conv5_2.weight'].copy_(x5)
            own_state['layer3.0.conv6_2.weight'].copy_(x6)
            own_state['layer3.0.conv7_2.weight'].copy_(x7)
            own_state['layer3.0.conv8_2.weight'].copy_(x8)
            own_state['layer3.0.conv9_2.weight'].copy_(x9)
            own_state['layer3.0.conv12_2.weight'].copy_(x12)
            own_state['layer3.0.conv22_2.weight'].copy_(x22)
            own_state['layer3.0.conv32_2.weight'].copy_(x32)
            own_state['layer3.0.conv42_2.weight'].copy_(x42)
            own_state['layer3.0.conv52_2.weight'].copy_(x52)
            own_state['layer3.0.conv62_2.weight'].copy_(x62)
            own_state['layer3.0.conv72_2.weight'].copy_(x72)
            own_state['layer3.0.conv82_2.weight'].copy_(x82)
            own_state['layer3.0.conv92_2.weight'].copy_(x92)
            continue

        if name == 'layer3.1.conv1.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9,x12,x22,x32,x42,x52,x62,x72,x82,x92 = split_conv_256(param)
            own_state['layer3.1.conv1.weight'].copy_(x1)
            own_state['layer3.1.conv2.weight'].copy_(x2)
            own_state['layer3.1.conv3.weight'].copy_(x3)
            own_state['layer3.1.conv4.weight'].copy_(x4)
            own_state['layer3.1.conv5.weight'].copy_(x5)
            own_state['layer3.1.conv6.weight'].copy_(x6)
            own_state['layer3.1.conv7.weight'].copy_(x7)
            own_state['layer3.1.conv8.weight'].copy_(x8)
            own_state['layer3.1.conv9.weight'].copy_(x9)
            own_state['layer3.1.conv12.weight'].copy_(x12)
            own_state['layer3.1.conv22.weight'].copy_(x22)
            own_state['layer3.1.conv32.weight'].copy_(x32)
            own_state['layer3.1.conv42.weight'].copy_(x42)
            own_state['layer3.1.conv52.weight'].copy_(x52)
            own_state['layer3.1.conv62.weight'].copy_(x62)
            own_state['layer3.1.conv72.weight'].copy_(x72)
            own_state['layer3.1.conv82.weight'].copy_(x82)
            own_state['layer3.1.conv92.weight'].copy_(x92)
            continue

        if name == 'layer3.1.conv2.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9,x12,x22,x32,x42,x52,x62,x72,x82,x92 = split_conv_256(param)
            own_state['layer3.1.conv1_2.weight'].copy_(x1)
            own_state['layer3.1.conv2_2.weight'].copy_(x2)
            own_state['layer3.1.conv3_2.weight'].copy_(x3)
            own_state['layer3.1.conv4_2.weight'].copy_(x4)
            own_state['layer3.1.conv5_2.weight'].copy_(x5)
            own_state['layer3.1.conv6_2.weight'].copy_(x6)
            own_state['layer3.1.conv7_2.weight'].copy_(x7)
            own_state['layer3.1.conv8_2.weight'].copy_(x8)
            own_state['layer3.1.conv9_2.weight'].copy_(x9)
            own_state['layer3.1.conv12_2.weight'].copy_(x12)
            own_state['layer3.1.conv22_2.weight'].copy_(x22)
            own_state['layer3.1.conv32_2.weight'].copy_(x32)
            own_state['layer3.1.conv42_2.weight'].copy_(x42)
            own_state['layer3.1.conv52_2.weight'].copy_(x52)
            own_state['layer3.1.conv62_2.weight'].copy_(x62)
            own_state['layer3.1.conv72_2.weight'].copy_(x72)
            own_state['layer3.1.conv82_2.weight'].copy_(x82)
            own_state['layer3.1.conv92_2.weight'].copy_(x92)
            continue

        if name == 'layer4.0.conv1.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9,x12,x22,x32,x42,x52,x62,x72,x82,x92 = split_conv_256(param)
            own_state['layer4.0.conv1.weight'].copy_(x1)
            own_state['layer4.0.conv2.weight'].copy_(x2)
            own_state['layer4.0.conv3.weight'].copy_(x3)
            own_state['layer4.0.conv4.weight'].copy_(x4)
            own_state['layer4.0.conv5.weight'].copy_(x5)
            own_state['layer4.0.conv6.weight'].copy_(x6)
            own_state['layer4.0.conv7.weight'].copy_(x7)
            own_state['layer4.0.conv8.weight'].copy_(x8)
            own_state['layer4.0.conv9.weight'].copy_(x9)
            own_state['layer4.0.conv12.weight'].copy_(x12)
            own_state['layer4.0.conv22.weight'].copy_(x22)
            own_state['layer4.0.conv32.weight'].copy_(x32)
            own_state['layer4.0.conv42.weight'].copy_(x42)
            own_state['layer4.0.conv52.weight'].copy_(x52)
            own_state['layer4.0.conv62.weight'].copy_(x62)
            own_state['layer4.0.conv72.weight'].copy_(x72)
            own_state['layer4.0.conv82.weight'].copy_(x82)
            own_state['layer4.0.conv92.weight'].copy_(x92)
            continue

        if name == 'layer4.0.conv2.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9,x12,x22,x32,x42,x52,x62,x72,x82,x92,x13,x23,x33,x43,x53,x63,x73,x83,x93,x14,x24,x34,x44,x54,x64,x74,x84,x94 = split_conv_512(param)
            own_state['layer4.0.conv1_2.weight'].copy_(x1)
            own_state['layer4.0.conv2_2.weight'].copy_(x2)
            own_state['layer4.0.conv3_2.weight'].copy_(x3)
            own_state['layer4.0.conv4_2.weight'].copy_(x4)
            own_state['layer4.0.conv5_2.weight'].copy_(x5)
            own_state['layer4.0.conv6_2.weight'].copy_(x6)
            own_state['layer4.0.conv7_2.weight'].copy_(x7)
            own_state['layer4.0.conv8_2.weight'].copy_(x8)
            own_state['layer4.0.conv9_2.weight'].copy_(x9)
            own_state['layer4.0.conv12_2.weight'].copy_(x12)
            own_state['layer4.0.conv22_2.weight'].copy_(x22)
            own_state['layer4.0.conv32_2.weight'].copy_(x32)
            own_state['layer4.0.conv42_2.weight'].copy_(x42)
            own_state['layer4.0.conv52_2.weight'].copy_(x52)
            own_state['layer4.0.conv62_2.weight'].copy_(x62)
            own_state['layer4.0.conv72_2.weight'].copy_(x72)
            own_state['layer4.0.conv82_2.weight'].copy_(x82)
            own_state['layer4.0.conv92_2.weight'].copy_(x92)
            own_state['layer4.0.conv13_2.weight'].copy_(x13)
            own_state['layer4.0.conv23_2.weight'].copy_(x23)
            own_state['layer4.0.conv33_2.weight'].copy_(x33)
            own_state['layer4.0.conv43_2.weight'].copy_(x43)
            own_state['layer4.0.conv53_2.weight'].copy_(x53)
            own_state['layer4.0.conv63_2.weight'].copy_(x63)
            own_state['layer4.0.conv73_2.weight'].copy_(x73)
            own_state['layer4.0.conv83_2.weight'].copy_(x83)
            own_state['layer4.0.conv93_2.weight'].copy_(x93)
            own_state['layer4.0.conv14_2.weight'].copy_(x14)
            own_state['layer4.0.conv24_2.weight'].copy_(x24)
            own_state['layer4.0.conv34_2.weight'].copy_(x34)
            own_state['layer4.0.conv44_2.weight'].copy_(x44)
            own_state['layer4.0.conv54_2.weight'].copy_(x54)
            own_state['layer4.0.conv64_2.weight'].copy_(x64)
            own_state['layer4.0.conv74_2.weight'].copy_(x74)
            own_state['layer4.0.conv84_2.weight'].copy_(x84)
            own_state['layer4.0.conv94_2.weight'].copy_(x94)
            continue

        if name == 'layer4.1.conv1.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9,x12,x22,x32,x42,x52,x62,x72,x82,x92,x13,x23,x33,x43,x53,x63,x73,x83,x93,x14,x24,x34,x44,x54,x64,x74,x84,x94 = split_conv_512(param)
            own_state['layer4.1.conv1.weight'].copy_(x1)
            own_state['layer4.1.conv2.weight'].copy_(x2)
            own_state['layer4.1.conv3.weight'].copy_(x3)
            own_state['layer4.1.conv4.weight'].copy_(x4)
            own_state['layer4.1.conv5.weight'].copy_(x5)
            own_state['layer4.1.conv6.weight'].copy_(x6)
            own_state['layer4.1.conv7.weight'].copy_(x7)
            own_state['layer4.1.conv8.weight'].copy_(x8)
            own_state['layer4.1.conv9.weight'].copy_(x9)
            own_state['layer4.1.conv12.weight'].copy_(x12)
            own_state['layer4.1.conv22.weight'].copy_(x22)
            own_state['layer4.1.conv32.weight'].copy_(x32)
            own_state['layer4.1.conv42.weight'].copy_(x42)
            own_state['layer4.1.conv52.weight'].copy_(x52)
            own_state['layer4.1.conv62.weight'].copy_(x62)
            own_state['layer4.1.conv72.weight'].copy_(x72)
            own_state['layer4.1.conv82.weight'].copy_(x82)
            own_state['layer4.1.conv92.weight'].copy_(x92)
            own_state['layer4.1.conv13.weight'].copy_(x13)
            own_state['layer4.1.conv23.weight'].copy_(x23)
            own_state['layer4.1.conv33.weight'].copy_(x33)
            own_state['layer4.1.conv43.weight'].copy_(x43)
            own_state['layer4.1.conv53.weight'].copy_(x53)
            own_state['layer4.1.conv63.weight'].copy_(x63)
            own_state['layer4.1.conv73.weight'].copy_(x73)
            own_state['layer4.1.conv83.weight'].copy_(x83)
            own_state['layer4.1.conv93.weight'].copy_(x93)
            own_state['layer4.1.conv14.weight'].copy_(x14)
            own_state['layer4.1.conv24.weight'].copy_(x24)
            own_state['layer4.1.conv34.weight'].copy_(x34)
            own_state['layer4.1.conv44.weight'].copy_(x44)
            own_state['layer4.1.conv54.weight'].copy_(x54)
            own_state['layer4.1.conv64.weight'].copy_(x64)
            own_state['layer4.1.conv74.weight'].copy_(x74)
            own_state['layer4.1.conv84.weight'].copy_(x84)
            own_state['layer4.1.conv94.weight'].copy_(x94)
            continue

        if name == 'layer4.1.conv2.weight':
            x1,x2,x3,x4,x5,x6,x7,x8,x9,x12,x22,x32,x42,x52,x62,x72,x82,x92,x13,x23,x33,x43,x53,x63,x73,x83,x93,x14,x24,x34,x44,x54,x64,x74,x84,x94 = split_conv_512(param)
            own_state['layer4.1.conv1_2.weight'].copy_(x1)
            own_state['layer4.1.conv2_2.weight'].copy_(x2)
            own_state['layer4.1.conv3_2.weight'].copy_(x3)
            own_state['layer4.1.conv4_2.weight'].copy_(x4)
            own_state['layer4.1.conv5_2.weight'].copy_(x5)
            own_state['layer4.1.conv6_2.weight'].copy_(x6)
            own_state['layer4.1.conv7_2.weight'].copy_(x7)
            own_state['layer4.1.conv8_2.weight'].copy_(x8)
            own_state['layer4.1.conv9_2.weight'].copy_(x9)
            own_state['layer4.1.conv12_2.weight'].copy_(x12)
            own_state['layer4.1.conv22_2.weight'].copy_(x22)
            own_state['layer4.1.conv32_2.weight'].copy_(x32)
            own_state['layer4.1.conv42_2.weight'].copy_(x42)
            own_state['layer4.1.conv52_2.weight'].copy_(x52)
            own_state['layer4.1.conv62_2.weight'].copy_(x62)
            own_state['layer4.1.conv72_2.weight'].copy_(x72)
            own_state['layer4.1.conv82_2.weight'].copy_(x82)
            own_state['layer4.1.conv92_2.weight'].copy_(x92)
            own_state['layer4.1.conv13_2.weight'].copy_(x13)
            own_state['layer4.1.conv23_2.weight'].copy_(x23)
            own_state['layer4.1.conv33_2.weight'].copy_(x33)
            own_state['layer4.1.conv43_2.weight'].copy_(x43)
            own_state['layer4.1.conv53_2.weight'].copy_(x53)
            own_state['layer4.1.conv63_2.weight'].copy_(x63)
            own_state['layer4.1.conv73_2.weight'].copy_(x73)
            own_state['layer4.1.conv83_2.weight'].copy_(x83)
            own_state['layer4.1.conv93_2.weight'].copy_(x93)
            own_state['layer4.1.conv14_2.weight'].copy_(x14)
            own_state['layer4.1.conv24_2.weight'].copy_(x24)
            own_state['layer4.1.conv34_2.weight'].copy_(x34)
            own_state['layer4.1.conv44_2.weight'].copy_(x44)
            own_state['layer4.1.conv54_2.weight'].copy_(x54)
            own_state['layer4.1.conv64_2.weight'].copy_(x64)
            own_state['layer4.1.conv74_2.weight'].copy_(x74)
            own_state['layer4.1.conv84_2.weight'].copy_(x84)
            own_state['layer4.1.conv94_2.weight'].copy_(x94)
            continue


        #copy step sizes
        if name == 'layer1.0.conv1.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer1.0.conv1.step_size'].copy_(param)
            own_state['layer1.0.conv2.step_size'].copy_(param)
            own_state['layer1.0.conv3.step_size'].copy_(param)
            own_state['layer1.0.conv4.step_size'].copy_(param)
            own_state['layer1.0.conv5.step_size'].copy_(param)
            own_state['layer1.0.conv6.step_size'].copy_(param)
            own_state['layer1.0.conv7.step_size'].copy_(param)
            own_state['layer1.0.conv8.step_size'].copy_(param)
            own_state['layer1.0.conv9.step_size'].copy_(param)
            continue

        if name == 'layer1.0.conv2.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer1.0.conv1_2.step_size'].copy_(param)
            own_state['layer1.0.conv2_2.step_size'].copy_(param)
            own_state['layer1.0.conv3_2.step_size'].copy_(param)
            own_state['layer1.0.conv4_2.step_size'].copy_(param)
            own_state['layer1.0.conv5_2.step_size'].copy_(param)
            own_state['layer1.0.conv6_2.step_size'].copy_(param)
            own_state['layer1.0.conv7_2.step_size'].copy_(param)
            own_state['layer1.0.conv8_2.step_size'].copy_(param)
            own_state['layer1.0.conv9_2.step_size'].copy_(param)
            continue

        if name == 'layer1.1.conv1.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer1.1.conv1.step_size'].copy_(param)
            own_state['layer1.1.conv2.step_size'].copy_(param)
            own_state['layer1.1.conv3.step_size'].copy_(param)
            own_state['layer1.1.conv4.step_size'].copy_(param)
            own_state['layer1.1.conv5.step_size'].copy_(param)
            own_state['layer1.1.conv6.step_size'].copy_(param)
            own_state['layer1.1.conv7.step_size'].copy_(param)
            own_state['layer1.1.conv8.step_size'].copy_(param)
            own_state['layer1.1.conv9.step_size'].copy_(param)
            continue

        if name == 'layer1.1.conv2.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer1.1.conv1_2.step_size'].copy_(param)
            own_state['layer1.1.conv2_2.step_size'].copy_(param)
            own_state['layer1.1.conv3_2.step_size'].copy_(param)
            own_state['layer1.1.conv4_2.step_size'].copy_(param)
            own_state['layer1.1.conv5_2.step_size'].copy_(param)
            own_state['layer1.1.conv6_2.step_size'].copy_(param)
            own_state['layer1.1.conv7_2.step_size'].copy_(param)
            own_state['layer1.1.conv8_2.step_size'].copy_(param)
            own_state['layer1.1.conv9_2.step_size'].copy_(param)
            continue

        if name == 'layer2.0.conv1.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer2.0.conv1.step_size'].copy_(param)
            own_state['layer2.0.conv2.step_size'].copy_(param)
            own_state['layer2.0.conv3.step_size'].copy_(param)
            own_state['layer2.0.conv4.step_size'].copy_(param)
            own_state['layer2.0.conv5.step_size'].copy_(param)
            own_state['layer2.0.conv6.step_size'].copy_(param)
            own_state['layer2.0.conv7.step_size'].copy_(param)
            own_state['layer2.0.conv8.step_size'].copy_(param)
            own_state['layer2.0.conv9.step_size'].copy_(param)
            continue

        if name == 'layer2.0.conv2.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer2.0.conv1_2.step_size'].copy_(param)
            own_state['layer2.0.conv2_2.step_size'].copy_(param)
            own_state['layer2.0.conv3_2.step_size'].copy_(param)
            own_state['layer2.0.conv4_2.step_size'].copy_(param)
            own_state['layer2.0.conv5_2.step_size'].copy_(param)
            own_state['layer2.0.conv6_2.step_size'].copy_(param)
            own_state['layer2.0.conv7_2.step_size'].copy_(param)
            own_state['layer2.0.conv8_2.step_size'].copy_(param)
            own_state['layer2.0.conv9_2.step_size'].copy_(param)
            continue

        if name == 'layer2.1.conv1.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer2.1.conv1.step_size'].copy_(param)
            own_state['layer2.1.conv2.step_size'].copy_(param)
            own_state['layer2.1.conv3.step_size'].copy_(param)
            own_state['layer2.1.conv4.step_size'].copy_(param)
            own_state['layer2.1.conv5.step_size'].copy_(param)
            own_state['layer2.1.conv6.step_size'].copy_(param)
            own_state['layer2.1.conv7.step_size'].copy_(param)
            own_state['layer2.1.conv8.step_size'].copy_(param)
            own_state['layer2.1.conv9.step_size'].copy_(param)
            continue

        if name == 'layer2.1.conv2.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer2.1.conv1_2.step_size'].copy_(param)
            own_state['layer2.1.conv2_2.step_size'].copy_(param)
            own_state['layer2.1.conv3_2.step_size'].copy_(param)
            own_state['layer2.1.conv4_2.step_size'].copy_(param)
            own_state['layer2.1.conv5_2.step_size'].copy_(param)
            own_state['layer2.1.conv6_2.step_size'].copy_(param)
            own_state['layer2.1.conv7_2.step_size'].copy_(param)
            own_state['layer2.1.conv8_2.step_size'].copy_(param)
            own_state['layer2.1.conv9_2.step_size'].copy_(param)
            continue

        if name == 'layer3.0.conv1.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer3.0.conv1.step_size'].copy_(param)
            own_state['layer3.0.conv2.step_size'].copy_(param)
            own_state['layer3.0.conv3.step_size'].copy_(param)
            own_state['layer3.0.conv4.step_size'].copy_(param)
            own_state['layer3.0.conv5.step_size'].copy_(param)
            own_state['layer3.0.conv6.step_size'].copy_(param)
            own_state['layer3.0.conv7.step_size'].copy_(param)
            own_state['layer3.0.conv8.step_size'].copy_(param)
            own_state['layer3.0.conv9.step_size'].copy_(param)
            continue

        if name == 'layer3.0.conv2.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer3.0.conv1_2.step_size'].copy_(param)
            own_state['layer3.0.conv2_2.step_size'].copy_(param)
            own_state['layer3.0.conv3_2.step_size'].copy_(param)
            own_state['layer3.0.conv4_2.step_size'].copy_(param)
            own_state['layer3.0.conv5_2.step_size'].copy_(param)
            own_state['layer3.0.conv6_2.step_size'].copy_(param)
            own_state['layer3.0.conv7_2.step_size'].copy_(param)
            own_state['layer3.0.conv8_2.step_size'].copy_(param)
            own_state['layer3.0.conv9_2.step_size'].copy_(param)
            own_state['layer3.0.conv12_2.step_size'].copy_(param)
            own_state['layer3.0.conv22_2.step_size'].copy_(param)
            own_state['layer3.0.conv32_2.step_size'].copy_(param)
            own_state['layer3.0.conv42_2.step_size'].copy_(param)
            own_state['layer3.0.conv52_2.step_size'].copy_(param)
            own_state['layer3.0.conv62_2.step_size'].copy_(param)
            own_state['layer3.0.conv72_2.step_size'].copy_(param)
            own_state['layer3.0.conv82_2.step_size'].copy_(param)
            own_state['layer3.0.conv92_2.step_size'].copy_(param)
            continue

        if name == 'layer3.1.conv1.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer3.1.conv1.step_size'].copy_(param)
            own_state['layer3.1.conv2.step_size'].copy_(param)
            own_state['layer3.1.conv3.step_size'].copy_(param)
            own_state['layer3.1.conv4.step_size'].copy_(param)
            own_state['layer3.1.conv5.step_size'].copy_(param)
            own_state['layer3.1.conv6.step_size'].copy_(param)
            own_state['layer3.1.conv7.step_size'].copy_(param)
            own_state['layer3.1.conv8.step_size'].copy_(param)
            own_state['layer3.1.conv9.step_size'].copy_(param)
            own_state['layer3.1.conv12.step_size'].copy_(param)
            own_state['layer3.1.conv22.step_size'].copy_(param)
            own_state['layer3.1.conv32.step_size'].copy_(param)
            own_state['layer3.1.conv42.step_size'].copy_(param)
            own_state['layer3.1.conv52.step_size'].copy_(param)
            own_state['layer3.1.conv62.step_size'].copy_(param)
            own_state['layer3.1.conv72.step_size'].copy_(param)
            own_state['layer3.1.conv82.step_size'].copy_(param)
            own_state['layer3.1.conv92.step_size'].copy_(param)
            continue

        if name == 'layer3.1.conv2.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer3.1.conv1_2.step_size'].copy_(param)
            own_state['layer3.1.conv2_2.step_size'].copy_(param)
            own_state['layer3.1.conv3_2.step_size'].copy_(param)
            own_state['layer3.1.conv4_2.step_size'].copy_(param)
            own_state['layer3.1.conv5_2.step_size'].copy_(param)
            own_state['layer3.1.conv6_2.step_size'].copy_(param)
            own_state['layer3.1.conv7_2.step_size'].copy_(param)
            own_state['layer3.1.conv8_2.step_size'].copy_(param)
            own_state['layer3.1.conv9_2.step_size'].copy_(param)
            own_state['layer3.1.conv12_2.step_size'].copy_(param)
            own_state['layer3.1.conv22_2.step_size'].copy_(param)
            own_state['layer3.1.conv32_2.step_size'].copy_(param)
            own_state['layer3.1.conv42_2.step_size'].copy_(param)
            own_state['layer3.1.conv52_2.step_size'].copy_(param)
            own_state['layer3.1.conv62_2.step_size'].copy_(param)
            own_state['layer3.1.conv72_2.step_size'].copy_(param)
            own_state['layer3.1.conv82_2.step_size'].copy_(param)
            own_state['layer3.1.conv92_2.step_size'].copy_(param)
            continue

        if name == 'layer4.0.conv1.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer4.0.conv1.step_size'].copy_(param)
            own_state['layer4.0.conv2.step_size'].copy_(param)
            own_state['layer4.0.conv3.step_size'].copy_(param)
            own_state['layer4.0.conv4.step_size'].copy_(param)
            own_state['layer4.0.conv5.step_size'].copy_(param)
            own_state['layer4.0.conv6.step_size'].copy_(param)
            own_state['layer4.0.conv7.step_size'].copy_(param)
            own_state['layer4.0.conv8.step_size'].copy_(param)
            own_state['layer4.0.conv9.step_size'].copy_(param)
            own_state['layer4.0.conv12.step_size'].copy_(param)
            own_state['layer4.0.conv22.step_size'].copy_(param)
            own_state['layer4.0.conv32.step_size'].copy_(param)
            own_state['layer4.0.conv42.step_size'].copy_(param)
            own_state['layer4.0.conv52.step_size'].copy_(param)
            own_state['layer4.0.conv62.step_size'].copy_(param)
            own_state['layer4.0.conv72.step_size'].copy_(param)
            own_state['layer4.0.conv82.step_size'].copy_(param)
            own_state['layer4.0.conv92.step_size'].copy_(param)
            continue

        if name == 'layer4.0.conv2.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer4.0.conv1_2.step_size'].copy_(param)
            own_state['layer4.0.conv2_2.step_size'].copy_(param)
            own_state['layer4.0.conv3_2.step_size'].copy_(param)
            own_state['layer4.0.conv4_2.step_size'].copy_(param)
            own_state['layer4.0.conv5_2.step_size'].copy_(param)
            own_state['layer4.0.conv6_2.step_size'].copy_(param)
            own_state['layer4.0.conv7_2.step_size'].copy_(param)
            own_state['layer4.0.conv8_2.step_size'].copy_(param)
            own_state['layer4.0.conv9_2.step_size'].copy_(param)
            own_state['layer4.0.conv12_2.step_size'].copy_(param)
            own_state['layer4.0.conv22_2.step_size'].copy_(param)
            own_state['layer4.0.conv32_2.step_size'].copy_(param)
            own_state['layer4.0.conv42_2.step_size'].copy_(param)
            own_state['layer4.0.conv52_2.step_size'].copy_(param)
            own_state['layer4.0.conv62_2.step_size'].copy_(param)
            own_state['layer4.0.conv72_2.step_size'].copy_(param)
            own_state['layer4.0.conv82_2.step_size'].copy_(param)
            own_state['layer4.0.conv92_2.step_size'].copy_(param)
            own_state['layer4.0.conv13_2.step_size'].copy_(param)
            own_state['layer4.0.conv23_2.step_size'].copy_(param)
            own_state['layer4.0.conv33_2.step_size'].copy_(param)
            own_state['layer4.0.conv43_2.step_size'].copy_(param)
            own_state['layer4.0.conv53_2.step_size'].copy_(param)
            own_state['layer4.0.conv63_2.step_size'].copy_(param)
            own_state['layer4.0.conv73_2.step_size'].copy_(param)
            own_state['layer4.0.conv83_2.step_size'].copy_(param)
            own_state['layer4.0.conv93_2.step_size'].copy_(param)
            own_state['layer4.0.conv14_2.step_size'].copy_(param)
            own_state['layer4.0.conv24_2.step_size'].copy_(param)
            own_state['layer4.0.conv34_2.step_size'].copy_(param)
            own_state['layer4.0.conv44_2.step_size'].copy_(param)
            own_state['layer4.0.conv54_2.step_size'].copy_(param)
            own_state['layer4.0.conv64_2.step_size'].copy_(param)
            own_state['layer4.0.conv74_2.step_size'].copy_(param)
            own_state['layer4.0.conv84_2.step_size'].copy_(param)
            own_state['layer4.0.conv94_2.step_size'].copy_(param)
            continue

        if name == 'layer4.1.conv1.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer4.1.conv1.step_size'].copy_(param)
            own_state['layer4.1.conv2.step_size'].copy_(param)
            own_state['layer4.1.conv3.step_size'].copy_(param)
            own_state['layer4.1.conv4.step_size'].copy_(param)
            own_state['layer4.1.conv5.step_size'].copy_(param)
            own_state['layer4.1.conv6.step_size'].copy_(param)
            own_state['layer4.1.conv7.step_size'].copy_(param)
            own_state['layer4.1.conv8.step_size'].copy_(param)
            own_state['layer4.1.conv9.step_size'].copy_(param)
            own_state['layer4.1.conv12.step_size'].copy_(param)
            own_state['layer4.1.conv22.step_size'].copy_(param)
            own_state['layer4.1.conv32.step_size'].copy_(param)
            own_state['layer4.1.conv42.step_size'].copy_(param)
            own_state['layer4.1.conv52.step_size'].copy_(param)
            own_state['layer4.1.conv62.step_size'].copy_(param)
            own_state['layer4.1.conv72.step_size'].copy_(param)
            own_state['layer4.1.conv82.step_size'].copy_(param)
            own_state['layer4.1.conv92.step_size'].copy_(param)
            own_state['layer4.1.conv13.step_size'].copy_(param)
            own_state['layer4.1.conv23.step_size'].copy_(param)
            own_state['layer4.1.conv33.step_size'].copy_(param)
            own_state['layer4.1.conv43.step_size'].copy_(param)
            own_state['layer4.1.conv53.step_size'].copy_(param)
            own_state['layer4.1.conv63.step_size'].copy_(param)
            own_state['layer4.1.conv73.step_size'].copy_(param)
            own_state['layer4.1.conv83.step_size'].copy_(param)
            own_state['layer4.1.conv93.step_size'].copy_(param)
            own_state['layer4.1.conv14.step_size'].copy_(param)
            own_state['layer4.1.conv24.step_size'].copy_(param)
            own_state['layer4.1.conv34.step_size'].copy_(param)
            own_state['layer4.1.conv44.step_size'].copy_(param)
            own_state['layer4.1.conv54.step_size'].copy_(param)
            own_state['layer4.1.conv64.step_size'].copy_(param)
            own_state['layer4.1.conv74.step_size'].copy_(param)
            own_state['layer4.1.conv84.step_size'].copy_(param)
            own_state['layer4.1.conv94.step_size'].copy_(param)
            continue

        if name == 'layer4.1.conv2.step_size':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer4.1.conv1_2.step_size'].copy_(param)
            own_state['layer4.1.conv2_2.step_size'].copy_(param)
            own_state['layer4.1.conv3_2.step_size'].copy_(param)
            own_state['layer4.1.conv4_2.step_size'].copy_(param)
            own_state['layer4.1.conv5_2.step_size'].copy_(param)
            own_state['layer4.1.conv6_2.step_size'].copy_(param)
            own_state['layer4.1.conv7_2.step_size'].copy_(param)
            own_state['layer4.1.conv8_2.step_size'].copy_(param)
            own_state['layer4.1.conv9_2.step_size'].copy_(param)
            own_state['layer4.1.conv12_2.step_size'].copy_(param)
            own_state['layer4.1.conv22_2.step_size'].copy_(param)
            own_state['layer4.1.conv32_2.step_size'].copy_(param)
            own_state['layer4.1.conv42_2.step_size'].copy_(param)
            own_state['layer4.1.conv52_2.step_size'].copy_(param)
            own_state['layer4.1.conv62_2.step_size'].copy_(param)
            own_state['layer4.1.conv72_2.step_size'].copy_(param)
            own_state['layer4.1.conv82_2.step_size'].copy_(param)
            own_state['layer4.1.conv92_2.step_size'].copy_(param)
            own_state['layer4.1.conv13_2.step_size'].copy_(param)
            own_state['layer4.1.conv23_2.step_size'].copy_(param)
            own_state['layer4.1.conv33_2.step_size'].copy_(param)
            own_state['layer4.1.conv43_2.step_size'].copy_(param)
            own_state['layer4.1.conv53_2.step_size'].copy_(param)
            own_state['layer4.1.conv63_2.step_size'].copy_(param)
            own_state['layer4.1.conv73_2.step_size'].copy_(param)
            own_state['layer4.1.conv83_2.step_size'].copy_(param)
            own_state['layer4.1.conv93_2.step_size'].copy_(param)
            own_state['layer4.1.conv14_2.step_size'].copy_(param)
            own_state['layer4.1.conv24_2.step_size'].copy_(param)
            own_state['layer4.1.conv34_2.step_size'].copy_(param)
            own_state['layer4.1.conv44_2.step_size'].copy_(param)
            own_state['layer4.1.conv54_2.step_size'].copy_(param)
            own_state['layer4.1.conv64_2.step_size'].copy_(param)
            own_state['layer4.1.conv74_2.step_size'].copy_(param)
            own_state['layer4.1.conv84_2.step_size'].copy_(param)
            own_state['layer4.1.conv94_2.step_size'].copy_(param)
            continue


        #init state
        if name == 'layer1.0.conv1.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer1.0.conv1.init_state'].copy_(param)
            own_state['layer1.0.conv2.init_state'].copy_(param)
            own_state['layer1.0.conv3.init_state'].copy_(param)
            own_state['layer1.0.conv4.init_state'].copy_(param)
            own_state['layer1.0.conv5.init_state'].copy_(param)
            own_state['layer1.0.conv6.init_state'].copy_(param)
            own_state['layer1.0.conv7.init_state'].copy_(param)
            own_state['layer1.0.conv8.init_state'].copy_(param)
            own_state['layer1.0.conv9.init_state'].copy_(param)
            continue

        if name == 'layer1.0.conv2.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer1.0.conv1_2.init_state'].copy_(param)
            own_state['layer1.0.conv2_2.init_state'].copy_(param)
            own_state['layer1.0.conv3_2.init_state'].copy_(param)
            own_state['layer1.0.conv4_2.init_state'].copy_(param)
            own_state['layer1.0.conv5_2.init_state'].copy_(param)
            own_state['layer1.0.conv6_2.init_state'].copy_(param)
            own_state['layer1.0.conv7_2.init_state'].copy_(param)
            own_state['layer1.0.conv8_2.init_state'].copy_(param)
            own_state['layer1.0.conv9_2.init_state'].copy_(param)
            continue

        if name == 'layer1.1.conv1.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer1.1.conv1.init_state'].copy_(param)
            own_state['layer1.1.conv2.init_state'].copy_(param)
            own_state['layer1.1.conv3.init_state'].copy_(param)
            own_state['layer1.1.conv4.init_state'].copy_(param)
            own_state['layer1.1.conv5.init_state'].copy_(param)
            own_state['layer1.1.conv6.init_state'].copy_(param)
            own_state['layer1.1.conv7.init_state'].copy_(param)
            own_state['layer1.1.conv8.init_state'].copy_(param)
            own_state['layer1.1.conv9.init_state'].copy_(param)
            continue

        if name == 'layer1.1.conv2.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer1.1.conv1_2.init_state'].copy_(param)
            own_state['layer1.1.conv2_2.init_state'].copy_(param)
            own_state['layer1.1.conv3_2.init_state'].copy_(param)
            own_state['layer1.1.conv4_2.init_state'].copy_(param)
            own_state['layer1.1.conv5_2.init_state'].copy_(param)
            own_state['layer1.1.conv6_2.init_state'].copy_(param)
            own_state['layer1.1.conv7_2.init_state'].copy_(param)
            own_state['layer1.1.conv8_2.init_state'].copy_(param)
            own_state['layer1.1.conv9_2.init_state'].copy_(param)
            continue

        if name == 'layer2.0.conv1.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer2.0.conv1.init_state'].copy_(param)
            own_state['layer2.0.conv2.init_state'].copy_(param)
            own_state['layer2.0.conv3.init_state'].copy_(param)
            own_state['layer2.0.conv4.init_state'].copy_(param)
            own_state['layer2.0.conv5.init_state'].copy_(param)
            own_state['layer2.0.conv6.init_state'].copy_(param)
            own_state['layer2.0.conv7.init_state'].copy_(param)
            own_state['layer2.0.conv8.init_state'].copy_(param)
            own_state['layer2.0.conv9.init_state'].copy_(param)
            continue

        if name == 'layer2.0.conv2.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer2.0.conv1_2.init_state'].copy_(param)
            own_state['layer2.0.conv2_2.init_state'].copy_(param)
            own_state['layer2.0.conv3_2.init_state'].copy_(param)
            own_state['layer2.0.conv4_2.init_state'].copy_(param)
            own_state['layer2.0.conv5_2.init_state'].copy_(param)
            own_state['layer2.0.conv6_2.init_state'].copy_(param)
            own_state['layer2.0.conv7_2.init_state'].copy_(param)
            own_state['layer2.0.conv8_2.init_state'].copy_(param)
            own_state['layer2.0.conv9_2.init_state'].copy_(param)
            continue

        if name == 'layer2.1.conv1.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer2.1.conv1.init_state'].copy_(param)
            own_state['layer2.1.conv2.init_state'].copy_(param)
            own_state['layer2.1.conv3.init_state'].copy_(param)
            own_state['layer2.1.conv4.init_state'].copy_(param)
            own_state['layer2.1.conv5.init_state'].copy_(param)
            own_state['layer2.1.conv6.init_state'].copy_(param)
            own_state['layer2.1.conv7.init_state'].copy_(param)
            own_state['layer2.1.conv8.init_state'].copy_(param)
            own_state['layer2.1.conv9.init_state'].copy_(param)
            continue

        if name == 'layer2.1.conv2.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer2.1.conv1_2.init_state'].copy_(param)
            own_state['layer2.1.conv2_2.init_state'].copy_(param)
            own_state['layer2.1.conv3_2.init_state'].copy_(param)
            own_state['layer2.1.conv4_2.init_state'].copy_(param)
            own_state['layer2.1.conv5_2.init_state'].copy_(param)
            own_state['layer2.1.conv6_2.init_state'].copy_(param)
            own_state['layer2.1.conv7_2.init_state'].copy_(param)
            own_state['layer2.1.conv8_2.init_state'].copy_(param)
            own_state['layer2.1.conv9_2.init_state'].copy_(param)
            continue

        if name == 'layer3.0.conv1.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer3.0.conv1.init_state'].copy_(param)
            own_state['layer3.0.conv2.init_state'].copy_(param)
            own_state['layer3.0.conv3.init_state'].copy_(param)
            own_state['layer3.0.conv4.init_state'].copy_(param)
            own_state['layer3.0.conv5.init_state'].copy_(param)
            own_state['layer3.0.conv6.init_state'].copy_(param)
            own_state['layer3.0.conv7.init_state'].copy_(param)
            own_state['layer3.0.conv8.init_state'].copy_(param)
            own_state['layer3.0.conv9.init_state'].copy_(param)
            continue

        if name == 'layer3.0.conv2.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer3.0.conv1_2.init_state'].copy_(param)
            own_state['layer3.0.conv2_2.init_state'].copy_(param)
            own_state['layer3.0.conv3_2.init_state'].copy_(param)
            own_state['layer3.0.conv4_2.init_state'].copy_(param)
            own_state['layer3.0.conv5_2.init_state'].copy_(param)
            own_state['layer3.0.conv6_2.init_state'].copy_(param)
            own_state['layer3.0.conv7_2.init_state'].copy_(param)
            own_state['layer3.0.conv8_2.init_state'].copy_(param)
            own_state['layer3.0.conv9_2.init_state'].copy_(param)
            own_state['layer3.0.conv12_2.init_state'].copy_(param)
            own_state['layer3.0.conv22_2.init_state'].copy_(param)
            own_state['layer3.0.conv32_2.init_state'].copy_(param)
            own_state['layer3.0.conv42_2.init_state'].copy_(param)
            own_state['layer3.0.conv52_2.init_state'].copy_(param)
            own_state['layer3.0.conv62_2.init_state'].copy_(param)
            own_state['layer3.0.conv72_2.init_state'].copy_(param)
            own_state['layer3.0.conv82_2.init_state'].copy_(param)
            own_state['layer3.0.conv92_2.init_state'].copy_(param)
            continue

        if name == 'layer3.1.conv1.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer3.1.conv1.init_state'].copy_(param)
            own_state['layer3.1.conv2.init_state'].copy_(param)
            own_state['layer3.1.conv3.init_state'].copy_(param)
            own_state['layer3.1.conv4.init_state'].copy_(param)
            own_state['layer3.1.conv5.init_state'].copy_(param)
            own_state['layer3.1.conv6.init_state'].copy_(param)
            own_state['layer3.1.conv7.init_state'].copy_(param)
            own_state['layer3.1.conv8.init_state'].copy_(param)
            own_state['layer3.1.conv9.init_state'].copy_(param)
            own_state['layer3.1.conv12.init_state'].copy_(param)
            own_state['layer3.1.conv22.init_state'].copy_(param)
            own_state['layer3.1.conv32.init_state'].copy_(param)
            own_state['layer3.1.conv42.init_state'].copy_(param)
            own_state['layer3.1.conv52.init_state'].copy_(param)
            own_state['layer3.1.conv62.init_state'].copy_(param)
            own_state['layer3.1.conv72.init_state'].copy_(param)
            own_state['layer3.1.conv82.init_state'].copy_(param)
            own_state['layer3.1.conv92.init_state'].copy_(param)
            continue

        if name == 'layer3.1.conv2.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer3.1.conv1_2.init_state'].copy_(param)
            own_state['layer3.1.conv2_2.init_state'].copy_(param)
            own_state['layer3.1.conv3_2.init_state'].copy_(param)
            own_state['layer3.1.conv4_2.init_state'].copy_(param)
            own_state['layer3.1.conv5_2.init_state'].copy_(param)
            own_state['layer3.1.conv6_2.init_state'].copy_(param)
            own_state['layer3.1.conv7_2.init_state'].copy_(param)
            own_state['layer3.1.conv8_2.init_state'].copy_(param)
            own_state['layer3.1.conv9_2.init_state'].copy_(param)
            own_state['layer3.1.conv12_2.init_state'].copy_(param)
            own_state['layer3.1.conv22_2.init_state'].copy_(param)
            own_state['layer3.1.conv32_2.init_state'].copy_(param)
            own_state['layer3.1.conv42_2.init_state'].copy_(param)
            own_state['layer3.1.conv52_2.init_state'].copy_(param)
            own_state['layer3.1.conv62_2.init_state'].copy_(param)
            own_state['layer3.1.conv72_2.init_state'].copy_(param)
            own_state['layer3.1.conv82_2.init_state'].copy_(param)
            own_state['layer3.1.conv92_2.init_state'].copy_(param)
            continue

        if name == 'layer4.0.conv1.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer4.0.conv1.init_state'].copy_(param)
            own_state['layer4.0.conv2.init_state'].copy_(param)
            own_state['layer4.0.conv3.init_state'].copy_(param)
            own_state['layer4.0.conv4.init_state'].copy_(param)
            own_state['layer4.0.conv5.init_state'].copy_(param)
            own_state['layer4.0.conv6.init_state'].copy_(param)
            own_state['layer4.0.conv7.init_state'].copy_(param)
            own_state['layer4.0.conv8.init_state'].copy_(param)
            own_state['layer4.0.conv9.init_state'].copy_(param)
            own_state['layer4.0.conv12.init_state'].copy_(param)
            own_state['layer4.0.conv22.init_state'].copy_(param)
            own_state['layer4.0.conv32.init_state'].copy_(param)
            own_state['layer4.0.conv42.init_state'].copy_(param)
            own_state['layer4.0.conv52.init_state'].copy_(param)
            own_state['layer4.0.conv62.init_state'].copy_(param)
            own_state['layer4.0.conv72.init_state'].copy_(param)
            own_state['layer4.0.conv82.init_state'].copy_(param)
            own_state['layer4.0.conv92.init_state'].copy_(param)
            continue

        if name == 'layer4.0.conv2.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer4.0.conv1_2.init_state'].copy_(param)
            own_state['layer4.0.conv2_2.init_state'].copy_(param)
            own_state['layer4.0.conv3_2.init_state'].copy_(param)
            own_state['layer4.0.conv4_2.init_state'].copy_(param)
            own_state['layer4.0.conv5_2.init_state'].copy_(param)
            own_state['layer4.0.conv6_2.init_state'].copy_(param)
            own_state['layer4.0.conv7_2.init_state'].copy_(param)
            own_state['layer4.0.conv8_2.init_state'].copy_(param)
            own_state['layer4.0.conv9_2.init_state'].copy_(param)
            own_state['layer4.0.conv12_2.init_state'].copy_(param)
            own_state['layer4.0.conv22_2.init_state'].copy_(param)
            own_state['layer4.0.conv32_2.init_state'].copy_(param)
            own_state['layer4.0.conv42_2.init_state'].copy_(param)
            own_state['layer4.0.conv52_2.init_state'].copy_(param)
            own_state['layer4.0.conv62_2.init_state'].copy_(param)
            own_state['layer4.0.conv72_2.init_state'].copy_(param)
            own_state['layer4.0.conv82_2.init_state'].copy_(param)
            own_state['layer4.0.conv92_2.init_state'].copy_(param)
            own_state['layer4.0.conv13_2.init_state'].copy_(param)
            own_state['layer4.0.conv23_2.init_state'].copy_(param)
            own_state['layer4.0.conv33_2.init_state'].copy_(param)
            own_state['layer4.0.conv43_2.init_state'].copy_(param)
            own_state['layer4.0.conv53_2.init_state'].copy_(param)
            own_state['layer4.0.conv63_2.init_state'].copy_(param)
            own_state['layer4.0.conv73_2.init_state'].copy_(param)
            own_state['layer4.0.conv83_2.init_state'].copy_(param)
            own_state['layer4.0.conv93_2.init_state'].copy_(param)
            own_state['layer4.0.conv14_2.init_state'].copy_(param)
            own_state['layer4.0.conv24_2.init_state'].copy_(param)
            own_state['layer4.0.conv34_2.init_state'].copy_(param)
            own_state['layer4.0.conv44_2.init_state'].copy_(param)
            own_state['layer4.0.conv54_2.init_state'].copy_(param)
            own_state['layer4.0.conv64_2.init_state'].copy_(param)
            own_state['layer4.0.conv74_2.init_state'].copy_(param)
            own_state['layer4.0.conv84_2.init_state'].copy_(param)
            own_state['layer4.0.conv94_2.init_state'].copy_(param)
            continue

        if name == 'layer4.1.conv1.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer4.1.conv1.init_state'].copy_(param)
            own_state['layer4.1.conv2.init_state'].copy_(param)
            own_state['layer4.1.conv3.init_state'].copy_(param)
            own_state['layer4.1.conv4.init_state'].copy_(param)
            own_state['layer4.1.conv5.init_state'].copy_(param)
            own_state['layer4.1.conv6.init_state'].copy_(param)
            own_state['layer4.1.conv7.init_state'].copy_(param)
            own_state['layer4.1.conv8.init_state'].copy_(param)
            own_state['layer4.1.conv9.init_state'].copy_(param)
            own_state['layer4.1.conv12.init_state'].copy_(param)
            own_state['layer4.1.conv22.init_state'].copy_(param)
            own_state['layer4.1.conv32.init_state'].copy_(param)
            own_state['layer4.1.conv42.init_state'].copy_(param)
            own_state['layer4.1.conv52.init_state'].copy_(param)
            own_state['layer4.1.conv62.init_state'].copy_(param)
            own_state['layer4.1.conv72.init_state'].copy_(param)
            own_state['layer4.1.conv82.init_state'].copy_(param)
            own_state['layer4.1.conv92.init_state'].copy_(param)
            own_state['layer4.1.conv13.init_state'].copy_(param)
            own_state['layer4.1.conv23.init_state'].copy_(param)
            own_state['layer4.1.conv33.init_state'].copy_(param)
            own_state['layer4.1.conv43.init_state'].copy_(param)
            own_state['layer4.1.conv53.init_state'].copy_(param)
            own_state['layer4.1.conv63.init_state'].copy_(param)
            own_state['layer4.1.conv73.init_state'].copy_(param)
            own_state['layer4.1.conv83.init_state'].copy_(param)
            own_state['layer4.1.conv93.init_state'].copy_(param)
            own_state['layer4.1.conv14.init_state'].copy_(param)
            own_state['layer4.1.conv24.init_state'].copy_(param)
            own_state['layer4.1.conv34.init_state'].copy_(param)
            own_state['layer4.1.conv44.init_state'].copy_(param)
            own_state['layer4.1.conv54.init_state'].copy_(param)
            own_state['layer4.1.conv64.init_state'].copy_(param)
            own_state['layer4.1.conv74.init_state'].copy_(param)
            own_state['layer4.1.conv84.init_state'].copy_(param)
            own_state['layer4.1.conv94.init_state'].copy_(param)
            continue

        if name == 'layer4.1.conv2.init_state':
            if isinstance(param, Parameter):
                param = param.data()
            own_state['layer4.1.conv1_2.init_state'].copy_(param)
            own_state['layer4.1.conv2_2.init_state'].copy_(param)
            own_state['layer4.1.conv3_2.init_state'].copy_(param)
            own_state['layer4.1.conv4_2.init_state'].copy_(param)
            own_state['layer4.1.conv5_2.init_state'].copy_(param)
            own_state['layer4.1.conv6_2.init_state'].copy_(param)
            own_state['layer4.1.conv7_2.init_state'].copy_(param)
            own_state['layer4.1.conv8_2.init_state'].copy_(param)
            own_state['layer4.1.conv9_2.init_state'].copy_(param)
            own_state['layer4.1.conv12_2.init_state'].copy_(param)
            own_state['layer4.1.conv22_2.init_state'].copy_(param)
            own_state['layer4.1.conv32_2.init_state'].copy_(param)
            own_state['layer4.1.conv42_2.init_state'].copy_(param)
            own_state['layer4.1.conv52_2.init_state'].copy_(param)
            own_state['layer4.1.conv62_2.init_state'].copy_(param)
            own_state['layer4.1.conv72_2.init_state'].copy_(param)
            own_state['layer4.1.conv82_2.init_state'].copy_(param)
            own_state['layer4.1.conv92_2.init_state'].copy_(param)
            own_state['layer4.1.conv13_2.init_state'].copy_(param)
            own_state['layer4.1.conv23_2.init_state'].copy_(param)
            own_state['layer4.1.conv33_2.init_state'].copy_(param)
            own_state['layer4.1.conv43_2.init_state'].copy_(param)
            own_state['layer4.1.conv53_2.init_state'].copy_(param)
            own_state['layer4.1.conv63_2.init_state'].copy_(param)
            own_state['layer4.1.conv73_2.init_state'].copy_(param)
            own_state['layer4.1.conv83_2.init_state'].copy_(param)
            own_state['layer4.1.conv93_2.init_state'].copy_(param)
            own_state['layer4.1.conv14_2.init_state'].copy_(param)
            own_state['layer4.1.conv24_2.init_state'].copy_(param)
            own_state['layer4.1.conv34_2.init_state'].copy_(param)
            own_state['layer4.1.conv44_2.init_state'].copy_(param)
            own_state['layer4.1.conv54_2.init_state'].copy_(param)
            own_state['layer4.1.conv64_2.init_state'].copy_(param)
            own_state['layer4.1.conv74_2.init_state'].copy_(param)
            own_state['layer4.1.conv84_2.init_state'].copy_(param)
            own_state['layer4.1.conv94_2.init_state'].copy_(param)
            continue

        #else: # 'init_state' in name
        #    #copy init_state to each
        #    continue

        if name not in own_state:
            #split conv
            continue
        if isinstance(param, Parameter):
            param = param.data()
        own_state[name].copy_(param)

    return model

